export const ADD_COMMENT = 'ADD_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING';//то блюда в настоящее время выбираются, возможно с сервера
export const DISHES_FAILED = 'DISHES_FAILED';//, что вам не удалось получить информацию о блюдах с сервера,
export const ADD_DISHES = 'ADD_DISHES';// что вы хотите добавить блюда в свой магазин.
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';